CREATE DATABASE IF NOT EXISTS `CSSECDV-MP` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `CSSECDV-MP`;

CREATE TABLE IF NOT EXISTS `accounts`(
`id` int (11) NOT NULL AUTO_INCREMENT,
`fname` VARCHAR (50) NOT NULL,
`lname` VARCHAR (50) NOT NULL,
`email` VARCHAR (50) NOT NULL,
`phone` VARCHAR(20) NOT NULL,
`password` VARBINARY(1024) NOT NULL,
`admin` BOOLEAN NOT NULL default FALSE,
`profile_pic` VARCHAR (50),
`birthday` DATE NULL,
PRIMARY KEY(`id`)

);
